(function(){
'use strict';
const C=FPICore,$=id=>document.getElementById(id),store=new C.DraftStore('sesion-aprendices');
let dirty=false,photos=[],learnerSignature=null,absences=[];
const TEMPLATE_KEY='fpi:session:templates';
let catalogPrograms=[];
const ORIGINAL_TEMPLATES=[
 'Presentación personal: Portar de forma decorosa el uniforme según horario establecido.',
 'Ambientes de formación: Conservar y mantener en buen estado, orden y aseo los ambientes de formación.',
 'Aseo personal: Presentar siempre las mejores condiciones de aseo y pulcritud personal.',
 'Expresiones: No usar expresiones grotescas en cualquier actividad y manifestar respeto.',
 'Cumplimientos: Cumplir con los trabajos asignados por los instructores y enviarlos puntualmente.',
 'Ahorro de energía: Usar responsablemente equipos, iluminación y aire acondicionado; evitar consumos innecesarios durante la jornada.'
];
const ABSENCE_TYPES={
 programada:{label:'Inasistencias programadas',reasons:[
  'Cita médica','Incapacidad médica','Citación a diligencias electorales o gubernamentales','Requerimiento de tipo laboral','Representación del SENA','Diligencia judicial','Actividad religiosa','Licencia de maternidad o paternidad'
 ]},
 noProgramada:{label:'Inasistencias no programadas',reasons:[
  'Muerte de algún familiar','Calamidad doméstica','Problemas de seguridad','Problemas de salud del aprendiz','Problemas de salud de un familiar dependiente de él','Urgencia con el estado de embarazo de la aprendiz','Urgencia de un familiar dependiente del aprendiz'
 ]},
 injustificado:{label:'Incumplimiento injustificado',reasons:[
  'No reporta ni justifica el incumplimiento dentro del plazo','Reporta dentro del plazo, pero la causa o los soportes no corresponden a un incumplimiento justificado'
 ]}
};
const UNJUSTIFIED_ART29='Según el Artículo 29 del Reglamento del Aprendiz SENA, se configura incumplimiento injustificado cuando el aprendiz no reporta ni justifica el incumplimiento ante el instructor previamente o dentro de los cinco (5) días hábiles siguientes a su ocurrencia con las respectivas evidencias; o cuando reporta la inasistencia dentro del plazo establecido, pero las causas y soportes no corresponden a las establecidas para incumplimientos justificados.';
const ABSENCE_NOTES={
 'Requerimiento de tipo laboral':'Este permiso no puede superar los tres (3) días en el trimestre, ya sea de manera continua o por intervalos.',
 'Actividad religiosa':'La actividad religiosa debe estar informada y contar con un plan de trabajo previamente acordado.',
 'Licencia de maternidad o paternidad':'La licencia debe estar expedida por la EPS correspondiente o por un médico competente.',
 'Muerte de algún familiar':'Según el Reglamento, será válida hasta el segundo grado de consanguinidad o afinidad. Se debe presentar copia del acta de defunción y el documento que demuestre el parentesco.',
 'Calamidad doméstica':'La calamidad doméstica debe estar soportada por un documento que evidencie la situación de fuerza mayor o caso fortuito.'
};
let templates=loadTemplates();
function loadTemplates(){try{const x=JSON.parse(localStorage.getItem(TEMPLATE_KEY)||'null');if(Array.isArray(x)&&x.length){const cleaned=x.filter(t=>!/^\s*Cursos\s*:/i.test(String(t?.text||'')));if(cleaned.length!==x.length)localStorage.setItem(TEMPLATE_KEY,JSON.stringify(cleaned));if(cleaned.length)return cleaned;}}catch(_){}return ORIGINAL_TEMPLATES.map(text=>({id:C.uid('tp'),enabled:true,text}));}
function saveTemplates(){localStorage.setItem(TEMPLATE_KEY,JSON.stringify(templates));}
function markDirty(){dirty=true;$('estadoTexto').textContent='Cambios sin guardar';}
function safeInt(v){const n=parseInt(String(v??'').replace(/\D/g,''),10);return Number.isFinite(n)&&n>=0?n:0;}
function absenceCount(){return absences.filter(x=>C.safe(x.name)).length;}
function attendanceCounts(){const active=safeInt($('totalActivos')?.value),absent=absenceCount();return{active,absent,present:Math.max(0,active-absent)};}
function reasonOptions(type,selected){const items=ABSENCE_TYPES[type]?.reasons||[];return `<option value="">Seleccione el motivo…</option>`+items.map(x=>`<option value="${C.esc(x)}" ${x===selected?'selected':''}>${C.esc(x)}</option>`).join('');}
function renderAbsences(){
 const box=$('absenceRows');if(!box)return;
 const counts=attendanceCounts();$('countActivos').textContent=String(counts.active);$('countAsistentes').textContent=String(counts.present);$('countInasistentes').textContent=String(counts.absent);
 if(!absences.length){box.innerHTML='<div class="session-absence-empty">No se han registrado inasistencias.</div>';return;}
 box.innerHTML=absences.map((x,i)=>`<div class="session-absence-row" data-id="${x.id}"><div class="session-absence-grid"><div class="fpi-field"><label for="absenceName_${i}">Aprendiz ${i+1}</label><input id="absenceName_${i}" name="absenceName_${i}" data-f="name" value="${C.esc(x.name||'')}" placeholder="Nombre completo"></div><div class="fpi-field"><label for="absenceType_${i}">Justificación</label><select id="absenceType_${i}" name="absenceType_${i}" data-f="type"><option value="programada" ${x.type==='programada'?'selected':''}>Inasistencias programadas</option><option value="noProgramada" ${x.type==='noProgramada'?'selected':''}>Inasistencias no programadas</option><option value="injustificado" ${x.type==='injustificado'?'selected':''}>Incumplimiento injustificado</option></select></div><div class="fpi-field"><label for="absenceReason_${i}">Motivo</label><select id="absenceReason_${i}" name="absenceReason_${i}" data-f="reason">${reasonOptions(x.type,x.reason)}</select></div><button class="fpi-btn small danger absence-remove" data-del type="button">Quitar</button></div>${ABSENCE_NOTES[x.reason]?`<div class="session-absence-note"><strong>Observación que quedará en el acta:</strong> ${C.esc(ABSENCE_NOTES[x.reason])}</div>`:''}</div>`).join('');
 box.querySelectorAll('.session-absence-row').forEach(row=>{
  const x=absences.find(a=>a.id===row.dataset.id);if(!x)return;
  row.querySelector('[data-f="name"]').oninput=e=>{x.name=e.target.value;markDirty();const c=attendanceCounts();$('countAsistentes').textContent=c.present;$('countInasistentes').textContent=c.absent;};
  row.querySelector('[data-f="type"]').onchange=e=>{x.type=e.target.value;x.reason='';markDirty();renderAbsences();};
  row.querySelector('[data-f="reason"]').onchange=e=>{x.reason=e.target.value;markDirty();renderAbsences();};
  row.querySelector('[data-del]').onclick=()=>{absences=absences.filter(a=>a.id!==x.id);markDirty();renderAbsences();};
 });
}
function addAbsence(){absences.push({id:C.uid('abs'),name:'',type:'programada',reason:''});renderAbsences();markDirty();setTimeout(()=>document.querySelector('#absenceRows .session-absence-row:last-child input')?.focus(),0);}
function init(){
 $('fecha').value=C.todayISO();$('horaInicio').value=C.nowTime();$('horaFin').value=C.nowTime(new Date(Date.now()+60*60000));
 autoLoadPrograms();renderTemplates();renderPhotos();renderAbsences();
 document.addEventListener('input',e=>{if(e.target.matches('input,textarea,select'))markDirty();});document.addEventListener('change',e=>{if(e.target.matches('input,textarea,select'))markDirty();});C.bindDirtyGuard(()=>dirty);
 $('totalActivos').addEventListener('input',renderAbsences);$('btnAddAbsence').onclick=addAbsence;
 $('btnAddTemplate').onclick=()=>{templates.push({id:C.uid('tp'),enabled:true,text:''});saveTemplates();renderTemplates();markDirty();};
 $('btnRestoreTemplates').onclick=()=>{if(!confirm('¿Restaurar las plantillas originales?'))return;templates=ORIGINAL_TEMPLATES.map(text=>({id:C.uid('tp'),enabled:true,text}));saveTemplates();renderTemplates();markDirty();};
 $('programa').addEventListener('change',refreshCompetencies);$('programa').addEventListener('input',()=>{clearTimeout(window.__fpiCompTimer);window.__fpiCompTimer=setTimeout(refreshCompetencies,350);});
 $('btnAgregarFotos').addEventListener('click',()=>{const f=$('fotosInput');if(f){f.value='';f.click();}});$('fotosInput').addEventListener('change',onPhotos);
 const sigRoot=$('sigAprendiz');if(sigRoot){let ready=false;C.bindSignatureWidget(sigRoot,s=>{learnerSignature=s;if(ready)markDirty();});sigRoot._setSignature(learnerSignature);ready=true;}
 $('btnGuardar').onclick=saveDraft;$('btnRecuperar').onclick=recoverDraft;$('btnValidar').onclick=()=>validate(true);$('btnVista').onclick=preview;$('btnDOCX').onclick=()=>download('docx');$('btnPDF').onclick=()=>download('pdf');
}
async function autoLoadPrograms(){
 const status=$('programCatalogStatus');
 try{if(status){status.textContent='Cargando catálogo local de programas…';status.style.color='';}if(!window.FPILocalCatalogs?.loadPrograms)throw new Error('No está disponible el cargador de catálogos locales.');const r=await window.FPILocalCatalogs.loadPrograms({force:true});catalogPrograms=r.programs||[];$('programasLocalListV4').innerHTML=catalogPrograms.map(x=>`<option value="${C.esc(x.nombre)}" label="${C.esc([x.codigo,x.nivel,x.version].filter(Boolean).join(' · '))}"></option>`).join('');if(status){const origen=r.source==='derived-design'?'derivado de horas_diseno.csv':r.source==='cache'?'copia local guardada':'programas.csv';status.textContent=`Catálogo local disponible: ${catalogPrograms.length} programas (${origen}).`;status.style.color='#296b35';}await refreshCompetencies();}
 catch(e){catalogPrograms=[];$('programasLocalListV4').innerHTML='';if(status){status.textContent='No fue posible cargar el catálogo local. Puede escribir el programa manualmente.';status.style.color='#b42318';}}
}
async function refreshCompetencies(){
 const dl=$('competenciasLocalListV4'),status=$('competenciaCatalogStatus'),name=C.safe($('programa').value);dl.innerHTML='';
 if(!name){if(status){status.textContent='Seleccione o escriba un programa. Si está en el catálogo, se cargarán sus competencias.';status.style.color='';}return;}
 try{if(!window.FPILocalCatalogs?.loadCompetenciesForProgram)throw new Error('No está disponible el catálogo local.');const wanted=C.norm(name),program=catalogPrograms.find(x=>C.norm(x.nombre)===wanted||C.safe(x.codigo)===C.safe(name))||name,r=await window.FPILocalCatalogs.loadCompetenciesForProgram(program);dl.innerHTML=(r.items||[]).map(x=>`<option value="${C.esc(x.competencia)}" label="${C.esc([x.codigoCompetencia,x.horas?x.horas+' h':''].filter(Boolean).join(' · '))}"></option>`).join('');if(status){const code=r.program?.codigo||'';status.textContent=r.items?.length?`${r.items.length} competencias cargadas desde horas_diseno.csv${code?' para el programa '+code:''}.`:'No hay competencias registradas para este programa en horas_diseno.csv. Puede escribir la competencia manualmente.';status.style.color=r.items?.length?'#296b35':'#8a5b00';}}
 catch(e){console.warn('[FPI] Competencias:',e);if(status){status.textContent='No fue posible leer horas_diseno.csv. Puede escribir la competencia manualmente.';status.style.color='#b42318';}}
}
function renderTemplates(){const box=$('templateRows');box.innerHTML=templates.map((x,i)=>`<div class="fpi-template-row" data-id="${x.id}"><input id="compromisoActivo_${i}" name="compromisoActivo_${i}" type="checkbox" ${x.enabled?'checked':''} aria-label="Activar compromiso"><textarea id="compromisoTexto_${i}" name="compromisoTexto_${i}" placeholder="Texto del compromiso">${C.esc(x.text)}</textarea><button class="fpi-btn small danger" type="button">Eliminar</button></div>`).join('');box.querySelectorAll('.fpi-template-row').forEach(r=>{const x=templates.find(t=>t.id===r.dataset.id);r.querySelector('input').onchange=e=>{x.enabled=e.target.checked;saveTemplates();markDirty();};r.querySelector('textarea').oninput=e=>{x.text=e.target.value;saveTemplates();markDirty();};r.querySelector('button').onclick=()=>{templates=templates.filter(t=>t.id!==x.id);saveTemplates();renderTemplates();markDirty();};});}
async function onPhotos(e){const files=Array.from(e.target.files||[]),status=$('photoStatus');if(!files.length)return;if(status){status.textContent=`Procesando ${files.length} fotografía(s)…`;status.style.color='';}let ok=0,fail=0;for(const f of files){try{if(!String(f.type||'').startsWith('image/'))throw new Error('El archivo no es una imagen.');let x;try{x=await C.optimizeImage(f,{maxSide:1500,quality:.78});}catch(optErr){const dataUrl=await C.readFileAsDataURL(f),im=await C.loadImage(dataUrl);x={dataUrl,width:im.naturalWidth||im.width||1200,height:im.naturalHeight||im.height||800};console.warn('[FPI] Se usó la fotografía original porque no fue posible optimizarla.',optErr);}photos.push({id:C.uid('ph'),name:f.name,...x});ok++;}catch(err){fail++;console.error('Foto no procesada',f.name,err);C.toast(`No se pudo procesar ${f.name}. Use JPG, PNG o WEBP.`,'error',4500);}}e.target.value='';renderPhotos();if(ok)markDirty();if(status){status.textContent=fail?`${ok} fotografía(s) agregadas; ${fail} no se pudieron procesar.`:`${ok} fotografía(s) agregadas correctamente.`;status.style.color=fail?'#8a5b00':'#296b35';}}
function renderPhotos(){const box=$('photoGrid');box.innerHTML=photos.map((p,i)=>`<div class="fpi-photo" data-id="${p.id}"><img src="${p.dataUrl}" alt="Foto ${i+1}"><div class="fpi-photo-actions"><button class="fpi-btn small" data-rot type="button">Rotar</button><button class="fpi-btn small" data-up type="button">↑</button><button class="fpi-btn small" data-down type="button">↓</button><button class="fpi-btn small danger" data-del type="button">Eliminar</button></div></div>`).join('');box.querySelectorAll('.fpi-photo').forEach(el=>{const i=photos.findIndex(p=>p.id===el.dataset.id),p=photos[i];el.querySelector('[data-rot]').onclick=async()=>{const x=await C.rotateDataUrl(p.dataUrl,90);Object.assign(p,x);renderPhotos();markDirty();};el.querySelector('[data-up]').onclick=()=>{if(i>0){[photos[i-1],photos[i]]=[photos[i],photos[i-1]];renderPhotos();markDirty();}};el.querySelector('[data-down]').onclick=()=>{if(i<photos.length-1){[photos[i+1],photos[i]]=[photos[i],photos[i+1]];renderPhotos();markDirty();}};el.querySelector('[data-del]').onclick=()=>{photos.splice(i,1);renderPhotos();markDirty();};});}
function fields(){const ids=['programa','ficha','totalActivos','competencia','actaNo','instructor','otroInstructor','protocolante','fecha','horaInicio','horaFin','ciudad','ambiente','regional','centro','reflexion','actividades','novedades','conclusiones'];return Object.fromEntries(ids.map(id=>[id,$(id).value]));}
function snapshot(){return{version:4,fields:fields(),templates:C.clone(templates),learnerSignature:C.clone(learnerSignature),absences:C.clone(absences)};}
function draftName(){return`Sesión · Ficha ${C.safe($('ficha').value)||'SIN FICHA'} · ${C.formatDate($('fecha').value||C.todayISO())}`;}
function saveDraft(){try{store.save(draftName(),snapshot());dirty=false;$('estadoTexto').textContent='Borrador guardado';$('estadoDetalle').textContent=draftName();C.toast('Borrador guardado. Las fotografías no se incluyen para evitar exceder el almacenamiento local.','success',4500);}catch(e){C.toast('No fue posible guardar: '+e.message,'error');}}
function applySnapshot(s){for(const[k,v]of Object.entries(s?.fields||{})){if($(k))$(k).value=v??'';}if(Array.isArray(s?.templates)){templates=s.templates;saveTemplates();renderTemplates();}absences=Array.isArray(s?.absences)?s.absences.map(x=>({...x,id:x.id||C.uid('abs')})):[];learnerSignature=s?.learnerSignature||null;if($('sigAprendiz')?._setSignature)$('sigAprendiz')._setSignature(learnerSignature);photos=[];renderPhotos();renderAbsences();refreshCompetencies();dirty=false;$('estadoTexto').textContent='Borrador recuperado';}
function recoverDraft(){const rows=store.list();if(!rows.length){C.toast('No hay borradores guardados.','info');return;}const html=`<div class="fpi-list">${rows.map(x=>`<button class="fpi-list-item fpi-list-button" type="button" data-name="${C.esc(x.name)}"><strong>${C.esc(x.name)}</strong><span>${new Date(x.updatedAt).toLocaleString('es-CO')}</span></button>`).join('')}</div>`;C.modal('Recuperar borrador',html);setTimeout(()=>document.querySelectorAll('.fpi-modal-body [data-name]').forEach(b=>b.onclick=()=>{applySnapshot(store.get(b.dataset.name)?.data);document.querySelector('.fpi-modal-x')?.click();}),0);}
function validate(show=false){const err=[];if(!C.safe($('programa').value))err.push('Diligencie el programa de formación.');if(!C.safe($('ficha').value))err.push('Diligencie el número de ficha.');const active=safeInt($('totalActivos').value);if(!active)err.push('Diligencie el total de aprendices activos.');if(!C.safe($('competencia').value))err.push('Diligencie la competencia.');if(!C.safe($('instructor').value))err.push('Diligencie el instructor gerente.');if(!C.safe($('fecha').value))err.push('Seleccione la fecha.');if(!C.safe($('horaInicio').value))err.push('Diligencie la hora de inicio.');if(!C.safe($('actividades').value))err.push('Registre las actividades desarrolladas.');if(absenceCount()>active&&active)err.push('La cantidad de inasistentes no puede superar el total de aprendices activos.');for(const x of absences){if(!C.safe(x.name)&&C.safe(x.reason))err.push('Hay una inasistencia con motivo pero sin nombre del aprendiz.');if(C.safe(x.name)&&!C.safe(x.reason))err.push(`Seleccione el motivo de la inasistencia de ${C.safe(x.name)}.`);}if(learnerSignature?.dataUrl&&!C.safe($('protocolante').value))err.push('Para incorporar la firma, diligencie el nombre del aprendiz protocolante.');const enabled=templates.filter(x=>x.enabled&&C.safe(x.text));if(!enabled.length)err.push('Active o agregue al menos un compromiso.');if(show){$('validationBox').innerHTML=err.length?`<div class="fpi-alert error"><strong>Revise la sesión:</strong><br>${err.map(C.esc).join('<br>')}</div>`:`<div class="fpi-alert ok">La sesión cumple las validaciones mínimas para generar el acta.</div>`;$('validationBox').scrollIntoView({behavior:'smooth',block:'center'});}return err;}
function absenceDevelopment(){const c=attendanceCounts(),named=absences.filter(x=>C.safe(x.name)),out=[{text:'4. Asistencia e inasistencias',bold:true},{text:`Aprendices activos: ${c.active} · Asistentes: ${c.present} · Inasistentes: ${c.absent}`}];if(!named.length){out.push({text:'No se registraron inasistencias.'});return out;}const unjustified=[];named.forEach((x,i)=>{const type=ABSENCE_TYPES[x.type]?.label||'Inasistencia',reason=C.safe(x.reason)||'Motivo no especificado';out.push({text:`${i+1}. ${C.upper(x.name)} · ${type} · ${reason}.`});if(x.type==='injustificado')unjustified.push(C.upper(x.name));else if(ABSENCE_NOTES[x.reason])out.push({text:`Observación: ${ABSENCE_NOTES[x.reason]}`});});if(unjustified.length)out.push({text:`Incumplimiento injustificado - Artículo 29. Aprendices relacionados: ${[...new Set(unjustified)].join(', ')}. ${UNJUSTIFIED_ART29}`});return out;}
function model(){const f=fields(),enabled=templates.filter(x=>x.enabled&&C.safe(x.text)),dev=[];if(C.safe(f.reflexion))dev.push({text:'1. Reflexión inicial',bold:true},{text:f.reflexion});dev.push({text:'2. Actividades desarrolladas',bold:true},{text:f.actividades});if(C.safe(f.novedades))dev.push({text:'3. Novedades / situaciones presentadas',bold:true},{text:f.novedades});dev.push(...absenceDevelopment());const attendees=[{name:C.upper(f.instructor),role:'INSTRUCTOR',approve:'SI',observation:''}];if(C.safe(f.otroInstructor))attendees.push({name:C.upper(f.otroInstructor),role:'INSTRUCTOR QUE IMPARTE',approve:'SI',observation:''});if(C.safe(f.protocolante))attendees.push({name:C.upper(f.protocolante),role:'APRENDIZ PROTOCOLANTE',approve:'SI',observation:'',signature:learnerSignature});return{actaNo:f.actaNo||'1',name:`SESIÓN DE FORMACIÓN · ${C.upper(f.programa)} · FICHA ${f.ficha}`,cityDate:'CIUDAD Y FECHA:',cityDateValue:`${C.upper(f.ciudad)}, ${C.formatLongDate(f.fecha)}`.replace(/^, /,''),startTime:f.horaInicio,endTime:f.horaFin,place:f.ambiente||'AMBIENTE DE FORMACIÓN',placeDetail:f.ambiente||'',regional:f.regional,center:f.centro,agenda:['Verificación de la sesión y participantes',`Desarrollo de la competencia: ${f.competencia}`,'Novedades e inasistencias','Conclusiones','Compromisos'],objective:`Registrar el desarrollo de la sesión de formación correspondiente a la competencia ${C.upper(f.competencia)}, así como las actividades realizadas, novedades, inasistencias, conclusiones y compromisos establecidos durante la jornada.`,development:dev,conclusions:f.conclusiones,commitments:enabled.map(x=>({activity:x.text,date:C.formatDate(f.fecha),responsible:`Aprendices Ficha ${f.ficha}`})),attendees,annexes:photos.map(x=>({dataUrl:x.dataUrl,width:x.width,height:x.height,name:x.name})),forceCalibri12:true};}
function bindPreviewUrl(url){setTimeout(()=>{const modal=document.querySelector('.fpi-modal-overlay:last-of-type');modal?.querySelector('.fpi-modal-x')?.addEventListener('click',()=>setTimeout(()=>URL.revokeObjectURL(url),500),{once:true});},0);}
async function preview(){if(validate(true).length)return;const old=$('btnVista').textContent;try{$('btnVista').disabled=true;$('btnVista').textContent='Preparando…';const blob=await GORF084Pdf.build(model()),url=URL.createObjectURL(blob);C.modal('Vista previa del documento',`<iframe title="Vista previa del acta" src="${url}" style="width:100%;height:74vh;border:0;background:#fff"></iframe>`,{wide:true});bindPreviewUrl(url);}catch(e){console.error(e);C.toast('No fue posible preparar la vista previa: '+e.message,'error');}finally{$('btnVista').disabled=false;$('btnVista').textContent=old;}}
function fileBase(){const f=fields(),fecha=String(f.fecha||C.todayISO()).replace(/\D/g,'').slice(0,8)||C.todayISO().replaceAll('-',''),ficha=C.slug(f.ficha||'FICHA'),raw=C.safe(f.protocolante)||C.safe(f.instructor)||'SIN NOMBRE';let name=C.slug(raw).replace(/_/g,' ');name=name.slice(0,15).trim().replace(/\s+/g,'_')||'SIN_PROTOCOLANT';return`PS_${fecha}_${ficha}_${name}`;}
async function download(kind){if(validate(true).length)return;const btn=$(kind==='docx'?'btnDOCX':'btnPDF'),old=btn.textContent,m=model();try{btn.disabled=true;btn.textContent='Generando…';const progress=(p,t)=>{$('estadoTexto').textContent=t||`Generando ${kind.toUpperCase()}`;$('estadoDetalle').textContent=`${p||0}%`;};const blob=kind==='docx'?await GORF084Docx.build(m,progress):await GORF084Pdf.build(m,progress);C.downloadBlob(blob,`${fileBase()}.${kind}`);dirty=false;$('estadoTexto').textContent=`${kind.toUpperCase()} generado`;$('estadoDetalle').textContent='Documento descargado correctamente.';C.toast(`${kind.toUpperCase()} generado correctamente.`,'success');}catch(e){console.error(e);C.toast('No fue posible generar el documento: '+e.message,'error');}finally{btn.disabled=false;btn.textContent=old;}}
init();
})();
